name: deploy_manager

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
runs-on: ubuntu-latest
env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      SERVER_IP: ${{secrets.SERVER_IP}}
      USER_NAME: ${{secrets.USER_NAME}} 
steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - run: npm install
    - run: npm run build
    - run: mkdir ~/.ssh
    - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
    - run: chmod 400 ~/.ssh/github-action
    - run: echo -e "Host \n\tUser $USER_NAME\n\tHostname $SERVER_IP\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
    - run: rsync -r ssh build ${{secrets.USER_NAME}}@${{secrets.SERVER_IP}}:~/manager
