name: deploy_manager

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
     runs-on: ubuntu-latest
     env:
        SSH_KEY: ${{secrets.SSH_KEY}}
        SERVER_IP: ${{secrets.SERVER_IP}}
        USER_NAME: ${{secrets.USER_NAME}} 
        process.env.CI: false
     steps:
       - uses: actions/checkout@v2
       - name: Use Node.js 16
         uses: actions/setup-node@v2
         with:
            node-version: 16
       - run: npm install
       - run: npm run build
       - name: rsync deployments
         uses: burnett01/rsync-deployments@5.2.1
         with:
           switches: -avzr --delete
           path: build/
           remote_path: ~/manager/
           remote_host: ${{secrets.SERVER_IP}}
           remote_user: ${{secrets.USER_NAME}} 
           remote_key:  ${{secrets.SSH_KEY}}
